version: '3.5'
services:
################################################################################
  nginx:
    container_name: nginx
    image: trash-anger/eval_devops2
    restart: always
    ports:
      - 8080:80
    volumes:
      - web:/var/www/html:rw
      - log:/var/log/nginx:rw
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
################################################################################
volumes:
  web:
  log:
